export const LOAD_REPO_DATA_INITIATED = "LOAD_REPO_DATA_INITIATED";
export const LOAD_REPO_DATA_SUCCESS = "LOAD_REPO_DATA_SUCCESS";
export const LOAD_REPO_DATA_ERROR = "LOAD_REPO_DATA_ERROR";

export const LOAD_DETAILS_DATA_INITIATED = "LOAD_DETAILS_DATA_INITIATED";
export const LOAD_DETAILS_DATA_SUCCESS = "LOAD_DETAILS_DATA_SUCCESS";
export const LOAD_DETAILS_DATA_ERROR = "LOAD_DETAILS_DATA_ERROR";
